# Generated by Django 5.0.7 on 2024-08-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="card_image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
