# Generated by Django 5.0.7 on 2024-08-05 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_card_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="user_id",
            new_name="user",
        ),
    ]
