# Generated by Django 5.0.7 on 2024-08-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_user_id_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
    ]
