# Generated by Django 5.0.7 on 2024-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("fruits", "Fruits"), ("vegetables", "Vegetables")],
                default="fruits",
                max_length=10,
                null=True,
            ),
        ),
    ]
